# Numpy
* https://numpy.org/devdocs/user/quickstart.html
* Numpy: Numerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료
* 순서가 있는 자료형
* 파이썬 list와의 차이는 자료형이 1가지만 들어감
* 우선순위 int < float < str

# 차원
* 0 차원: 점 . 스칼라
* 1 차원: 선 --- 방향이 없는 벡터, 배열, list, tuple {1,2,3,4}
* 2 차원: 면 가로, 세로, DB 테이블, DataFrame, excel Sheet, matrix, 행렬
* 3 차원: 입체, 가로, 세로, 깊이, 정육면체(주사위), 2차원 데이터의 묶음, excel file
* 4 차원: 3차원 데이터의 묶음
* 5 차원: 4차원 데이터의 묶음

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
num = 10

* 차원을 출력하는 메서디 .ndim
* 차원의 형태를 출력하는 메서드 .shape

* 리스트 개수 = 행(row)
* 각 리스트 안의 원소 개수 = 열(column)

In [7]:
num.ndim # 차원이 없음

AttributeError: 'int' object has no attribute 'ndim'

In [6]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [8]:
# ndarray는 방향이 없는 벡터 # (행, 열)
a.shape

(5,)

In [10]:
# 세로로 방향을 가진 열벡터
a2 = np.array([[1], [2], [3], [4], [5]])
a2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
a2.shape

(5, 1)

In [12]:
a2.ndim

2

In [14]:
# 행이 1개고 열이 여러개인 행벡터
a3 = np.array([[1,2,3,4,5]])
a3

array([[1, 2, 3, 4, 5]])

In [15]:
a.ndim

1

In [16]:
a.shape

(5,)

# 2차원 데이터

In [17]:
d2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
print(d2.ndim, d2.shape)

2 (2, 5)


# 3차원 데이터

In [19]:
d3 = np.array([[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]])
d3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [25]:
print(d3.ndim, d3.shape) # 3차원 shape = (덩어리 수, 행 수, 열 수)

3 (4, 2, 5)


# 4차원 데이터

In [21]:
d4 = np.array([[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], 
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]])
d4

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [23]:
print(d4.ndim, d4.shape) # 4차원 = (덩어리, 묶음, 행, 열)

4 (2, 4, 2, 5)


# 5차원 데이터

In [22]:
d5 = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], 
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]])
d5

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [26]:
print(d5.ndim, d5.shape)

5 (1, 2, 4, 2, 5)


In [27]:
l5 = [[[[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]], 
              [[[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]], [[1,2,3,4,5], [6,7,8,9,10]]]]]
l5

[[[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]],
  [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
   [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]]]]

# Numpy를 사용해야 하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [28]:
#  스칼라 연산
a = 10
b = 5
scalar = a + b
scalar

15

In [30]:
# 1차원 벡터의 연산
v1 = [1,2,3,4,5]
# v1 요소에 10을 곱한 리스트로 만드세요
mul10 = []
for num in v1:
    mul10.append(num*10)
mul10

[10, 20, 30, 40, 50]

In [34]:
# 3차원 데이터에 10을 곱하는 연산
result3 = []
for item1 in d3:
    temp2 = []
    for item2 in item1:
        temp1 = []
        for item3 in item2:
            temp1.append(item3 * 10)
        temp2.append(temp1)
    result3.append(item2)
result3 = np.array(result3)
print(result3, "\n", result3.ndim, result3.shape)

[[ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]] 
 2 (4, 5)


# numpy에서 자주 사용하는 메서드
* .ndim: 몇 차원인지 확인
* .shape: 몇 차원, 몇 행, 몇 열인지 구조를 확인
* .size: 배열 안에 있는 요소의 총 개수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지

# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣음

In [35]:
e1 = np.array([1,2,3,4,5])
e1

array([1, 2, 3, 4, 5])

In [36]:
e2 = np.array((1,2,3,4,5))
e2

# np.array()는 리스트([])든 튜플(())이든 순서 있는 자료형”이면 그대로 배열로 바꿔줌

array([1, 2, 3, 4, 5])

In [38]:
e3 = np.array((1,2,3,4,5))
print(e3, e3.dtype)

[1 2 3 4 5] int64


In [37]:
e4 = np.array((1, 2, 3.0, "4", 5))
print(e4, e4.dtype)

['1' '2' '3.0' '4' '5'] <U32


# np.arange(시작, 끝, step)

In [39]:
a = np.arange(1, 11, 2)
a

array([1, 3, 5, 7, 9])

# .reshape(행, 열)
* 벡터를 원하는 크기의 다차원 배열로 변환

In [40]:
a4 = a3.reshape(5, 2, 2, 5)
print(a4.ndim, a4.shape)

ValueError: cannot reshape array of size 5 into shape (5,2,2,5)

In [ ]:
a5 = a3.reshape(-1, 1, 2, 2, 5)
print(a5.ndim, a4.shape)

# flatten()
* 다차원 배열을 1차원으로 펼쳐줌

In [41]:
a4.ndim

NameError: name 'a4' is not defined

In [43]:
a6 = a5.flatten()
print(a6.ndim, a6.shape)
a6

NameError: name 'a5' is not defined

# np.flip()
* 행렬의 순서를 뒤집을 때

In [44]:
a5

NameError: name 'a5' is not defined

# np.linspace(시작, 끝, 구간 수)
* 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때

In [45]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
np.linspace(1, 10, 33)

array([ 1.     ,  1.28125,  1.5625 ,  1.84375,  2.125  ,  2.40625,
        2.6875 ,  2.96875,  3.25   ,  3.53125,  3.8125 ,  4.09375,
        4.375  ,  4.65625,  4.9375 ,  5.21875,  5.5    ,  5.78125,
        6.0625 ,  6.34375,  6.625  ,  6.90625,  7.1875 ,  7.46875,
        7.75   ,  8.03125,  8.3125 ,  8.59375,  8.875  ,  9.15625,
        9.4375 ,  9.71875, 10.     ])

# argsort()
* 자료 중 값을 작은 것에서 큰 순으로 원래 인덱스 출력

In [47]:
g = np.array([5, 0.5, -7, 42, 10, 0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [48]:
s = g.argsort()
s

array([2, 5, 1, 0, 4, 3])